# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c240126572bdca76b1cececd121074fc4b6f1d9ea109e9a48422339b7864e0a0cfd423ba34bf25495acdcb5ca4e95253af0f4eb7d8b7328db646fc97c95fa30

test:
  secret_key_base: 7b7666b14d74a4e90a1d92e840031f327941b7e94c2431cdbc2dc7d0f4aafc714a37af56df3e2d1a2cd9620446fb7b3ca23a2631b8c474c5cb5d04caf2473444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
